#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DialogSampleApp.Resource", IsApplication=true)]

namespace DialogSampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Android.Dialog.Resource.Drawable.dialog_disclosure = DialogSampleApp.Resource.Drawable.dialog_disclosure;
			Android.Dialog.Resource.Drawable.expander_ic_minimized = DialogSampleApp.Resource.Drawable.expander_ic_minimized;
			Android.Dialog.Resource.Id.dialog_BoolField = DialogSampleApp.Resource.Id.dialog_BoolField;
			Android.Dialog.Resource.Id.dialog_Button = DialogSampleApp.Resource.Id.dialog_Button;
			Android.Dialog.Resource.Id.dialog_DisclosureField = DialogSampleApp.Resource.Id.dialog_DisclosureField;
			Android.Dialog.Resource.Id.dialog_HtmlField = DialogSampleApp.Resource.Id.dialog_HtmlField;
			Android.Dialog.Resource.Id.dialog_ImageLeft = DialogSampleApp.Resource.Id.dialog_ImageLeft;
			Android.Dialog.Resource.Id.dialog_ImageRight = DialogSampleApp.Resource.Id.dialog_ImageRight;
			Android.Dialog.Resource.Id.dialog_LabelField = DialogSampleApp.Resource.Id.dialog_LabelField;
			Android.Dialog.Resource.Id.dialog_LabelPercentageField = DialogSampleApp.Resource.Id.dialog_LabelPercentageField;
			Android.Dialog.Resource.Id.dialog_LabelSubtextField = DialogSampleApp.Resource.Id.dialog_LabelSubtextField;
			Android.Dialog.Resource.Id.dialog_Panel = DialogSampleApp.Resource.Id.dialog_Panel;
			Android.Dialog.Resource.Id.dialog_RadioButtonList = DialogSampleApp.Resource.Id.dialog_RadioButtonList;
			Android.Dialog.Resource.Id.dialog_SliderField = DialogSampleApp.Resource.Id.dialog_SliderField;
			Android.Dialog.Resource.Id.dialog_Spinner = DialogSampleApp.Resource.Id.dialog_Spinner;
			Android.Dialog.Resource.Id.dialog_ValueField = DialogSampleApp.Resource.Id.dialog_ValueField;
			Android.Dialog.Resource.Layout.dialog_achievements = DialogSampleApp.Resource.Layout.dialog_achievements;
			Android.Dialog.Resource.Layout.dialog_boolfieldleft = DialogSampleApp.Resource.Layout.dialog_boolfieldleft;
			Android.Dialog.Resource.Layout.dialog_boolfieldright = DialogSampleApp.Resource.Layout.dialog_boolfieldright;
			Android.Dialog.Resource.Layout.dialog_boolfieldsubleft = DialogSampleApp.Resource.Layout.dialog_boolfieldsubleft;
			Android.Dialog.Resource.Layout.dialog_boolfieldsubright = DialogSampleApp.Resource.Layout.dialog_boolfieldsubright;
			Android.Dialog.Resource.Layout.dialog_button = DialogSampleApp.Resource.Layout.dialog_button;
			Android.Dialog.Resource.Layout.dialog_datefield = DialogSampleApp.Resource.Layout.dialog_datefield;
			Android.Dialog.Resource.Layout.dialog_fieldsetlabel = DialogSampleApp.Resource.Layout.dialog_fieldsetlabel;
			Android.Dialog.Resource.Layout.dialog_floatimage = DialogSampleApp.Resource.Layout.dialog_floatimage;
			Android.Dialog.Resource.Layout.dialog_html = DialogSampleApp.Resource.Layout.dialog_html;
			Android.Dialog.Resource.Layout.dialog_labelfieldbelow = DialogSampleApp.Resource.Layout.dialog_labelfieldbelow;
			Android.Dialog.Resource.Layout.dialog_labelfieldright = DialogSampleApp.Resource.Layout.dialog_labelfieldright;
			Android.Dialog.Resource.Layout.dialog_multiline_labelfieldbelow = DialogSampleApp.Resource.Layout.dialog_multiline_labelfieldbelow;
			Android.Dialog.Resource.Layout.dialog_onofffieldright = DialogSampleApp.Resource.Layout.dialog_onofffieldright;
			Android.Dialog.Resource.Layout.dialog_panel = DialogSampleApp.Resource.Layout.dialog_panel;
			Android.Dialog.Resource.Layout.dialog_root = DialogSampleApp.Resource.Layout.dialog_root;
			Android.Dialog.Resource.Layout.dialog_selectlist = DialogSampleApp.Resource.Layout.dialog_selectlist;
			Android.Dialog.Resource.Layout.dialog_selectlistfield = DialogSampleApp.Resource.Layout.dialog_selectlistfield;
			Android.Dialog.Resource.Layout.dialog_textarea = DialogSampleApp.Resource.Layout.dialog_textarea;
			Android.Dialog.Resource.Layout.dialog_textfieldbelow = DialogSampleApp.Resource.Layout.dialog_textfieldbelow;
			Android.Dialog.Resource.Layout.dialog_textfieldright = DialogSampleApp.Resource.Layout.dialog_textfieldright;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int expander_ic_minimized = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int spinner_default_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int spinner_default_holo_light = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int button_bar = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button_done = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int button_revert = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int dialog_BoolField = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int dialog_Button = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int dialog_DisclosureField = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int dialog_HtmlField = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ImageLeft = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int dialog_ImageRight = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int dialog_LabelPercentageField = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int dialog_LabelSubtextField = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_Panel = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_RadioButtonList = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int dialog_SliderField = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int dialog_Spinner = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int dialog_ValueField = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_string_element = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_achievements = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldleft = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldright = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubleft = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_boolfieldsubright = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_button = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_datefield = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_fieldsetlabel = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_floatimage = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_html = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labeldisclosure = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_labelfieldbelow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_labelfieldright = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_multiline_labelfieldbelow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_onofffieldright = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_panel = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_root = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlist = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_selectlistfield = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textarea = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldbelow = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_textfieldright = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int form_with_buttons = 2130903063;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
